// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.30.1
// source: multiplexing.proto

// 定义包名 Package names are used to prevent name clashes between protocol message types
//and also will be used to generate code.

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Items         []string               `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         float32                `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	Destination   string                 `protobuf:"bytes,5,opt,name=destination,proto3" json:"destination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_multiplexing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_multiplexing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_multiplexing_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Order) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Order) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Order) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

type CombinedShipment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	OrdersList    []*Order               `protobuf:"bytes,3,rep,name=ordersList,proto3" json:"ordersList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CombinedShipment) Reset() {
	*x = CombinedShipment{}
	mi := &file_multiplexing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombinedShipment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombinedShipment) ProtoMessage() {}

func (x *CombinedShipment) ProtoReflect() protoreflect.Message {
	mi := &file_multiplexing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombinedShipment.ProtoReflect.Descriptor instead.
func (*CombinedShipment) Descriptor() ([]byte, []int) {
	return file_multiplexing_proto_rawDescGZIP(), []int{1}
}

func (x *CombinedShipment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CombinedShipment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CombinedShipment) GetOrdersList() []*Order {
	if x != nil {
		return x.OrdersList
	}
	return nil
}

var File_multiplexing_proto protoreflect.FileDescriptor

const file_multiplexing_proto_rawDesc = "" +
	"\n" +
	"\x12multiplexing.proto\x12\x05proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x87\x01\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05items\x18\x02 \x03(\tR\x05items\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x02R\x05price\x12 \n" +
	"\vdestination\x18\x05 \x01(\tR\vdestination\"h\n" +
	"\x10CombinedShipment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12,\n" +
	"\n" +
	"ordersList\x18\x03 \x03(\v2\f.proto.OrderR\n" +
	"ordersList2\xd3\x02\n" +
	"\x0fOrderManagement\x128\n" +
	"\baddOrder\x12\f.proto.Order\x1a\x1c.google.protobuf.StringValue\"\x00\x128\n" +
	"\bgetOrder\x12\x1c.google.protobuf.StringValue\x1a\f.proto.Order\"\x00\x12>\n" +
	"\fsearchOrders\x12\x1c.google.protobuf.StringValue\x1a\f.proto.Order\"\x000\x01\x12>\n" +
	"\fupdateOrders\x12\f.proto.Order\x1a\x1c.google.protobuf.StringValue\"\x00(\x01\x12L\n" +
	"\rprocessOrders\x12\x1c.google.protobuf.StringValue\x1a\x17.proto.CombinedShipment\"\x00(\x010\x01B\x03Z\x01.b\x06proto3"

var (
	file_multiplexing_proto_rawDescOnce sync.Once
	file_multiplexing_proto_rawDescData []byte
)

func file_multiplexing_proto_rawDescGZIP() []byte {
	file_multiplexing_proto_rawDescOnce.Do(func() {
		file_multiplexing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_multiplexing_proto_rawDesc), len(file_multiplexing_proto_rawDesc)))
	})
	return file_multiplexing_proto_rawDescData
}

var file_multiplexing_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_multiplexing_proto_goTypes = []any{
	(*Order)(nil),                  // 0: proto.Order
	(*CombinedShipment)(nil),       // 1: proto.CombinedShipment
	(*wrapperspb.StringValue)(nil), // 2: google.protobuf.StringValue
}
var file_multiplexing_proto_depIdxs = []int32{
	0, // 0: proto.CombinedShipment.ordersList:type_name -> proto.Order
	0, // 1: proto.OrderManagement.addOrder:input_type -> proto.Order
	2, // 2: proto.OrderManagement.getOrder:input_type -> google.protobuf.StringValue
	2, // 3: proto.OrderManagement.searchOrders:input_type -> google.protobuf.StringValue
	0, // 4: proto.OrderManagement.updateOrders:input_type -> proto.Order
	2, // 5: proto.OrderManagement.processOrders:input_type -> google.protobuf.StringValue
	2, // 6: proto.OrderManagement.addOrder:output_type -> google.protobuf.StringValue
	0, // 7: proto.OrderManagement.getOrder:output_type -> proto.Order
	0, // 8: proto.OrderManagement.searchOrders:output_type -> proto.Order
	2, // 9: proto.OrderManagement.updateOrders:output_type -> google.protobuf.StringValue
	1, // 10: proto.OrderManagement.processOrders:output_type -> proto.CombinedShipment
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_multiplexing_proto_init() }
func file_multiplexing_proto_init() {
	if File_multiplexing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_multiplexing_proto_rawDesc), len(file_multiplexing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_multiplexing_proto_goTypes,
		DependencyIndexes: file_multiplexing_proto_depIdxs,
		MessageInfos:      file_multiplexing_proto_msgTypes,
	}.Build()
	File_multiplexing_proto = out.File
	file_multiplexing_proto_goTypes = nil
	file_multiplexing_proto_depIdxs = nil
}
